name: CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js in ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          - npm ci

      - name: Lint code
        run: |
          - npm run lint

      - name: Test code
        run: |
          - npm test

      - name: Package
        run: |
          - npm run package
