name: CD-App

on:
  push:
    branches:
      - 'master'
      - 'v0.3.0'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    needs: "test"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js in ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Build/release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
        env:
          CI: ""

